"""
Evaluate VADER and FinBERT on local benchmark finance sentiment datasets.

Output: data/processed/sentiment_eval_report.csv

Example:
  python -m src.evaluate_sentiment
  python -m src.evaluate_sentiment --models vader,finbert
"""
from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

from src.dataset_loaders import (
    concat_training_views,
    load_combined_two_column_csv,
    load_financial_phrasebank_all_agree,
)
from src.sentiment_engines import SUPPORTED_ENGINES, get_engine, label_from_compound

PROJECT_ROOT = Path(__file__).resolve().parent.parent
EVAL_OUT = PROJECT_ROOT / "data" / "processed" / "sentiment_eval_report.csv"
EVAL_SUMMARY_OUT = PROJECT_ROOT / "data" / "processed" / "sentiment_eval_report.md"
VADER_LEGACY_OUT = PROJECT_ROOT / "data" / "processed" / "vader_eval_report.csv"

FINBERT_MODEL_ID = "ProsusAI/finbert"


def _accuracy(y_true: list[str], y_pred: list[str]) -> float:
    if not y_true:
        return 0.0
    return sum(t == p for t, p in zip(y_true, y_pred)) / len(y_true)


def _macro_f1(y_true: list[str], y_pred: list[str], labels: list[str]) -> float:
    f1s: list[float] = []
    for label in labels:
        tp = sum(1 for t, p in zip(y_true, y_pred) if t == label and p == label)
        fp = sum(1 for t, p in zip(y_true, y_pred) if t != label and p == label)
        fn = sum(1 for t, p in zip(y_true, y_pred) if t == label and p != label)
        if tp == 0 and fp == 0 and fn == 0:
            continue
        precision = tp / (tp + fp) if (tp + fp) else 0.0
        recall = tp / (tp + fn) if (tp + fn) else 0.0
        f1 = 2 * precision * recall / (precision + recall) if (precision + recall) else 0.0
        f1s.append(f1)
    return sum(f1s) / len(f1s) if f1s else 0.0


def evaluate_dataframe(
    df: pd.DataFrame,
    dataset_name: str,
    *,
    engine_name: str,
) -> dict[str, object]:
    work = df.dropna(subset=["text", "label"]).copy()
    work["text"] = work["text"].astype(str).str.strip()
    work = work[work["text"].str.len() > 0]
    if work.empty:
        return {
            "model": engine_name,
            "dataset": dataset_name,
            "samples": 0,
            "accuracy": 0.0,
            "macro_f1": 0.0,
            "positive_acc": 0.0,
            "neutral_acc": 0.0,
            "negative_acc": 0.0,
        }

    engine = get_engine(engine_name)
    texts = work["text"].tolist()
    y_true = work["label"].astype(str).str.lower().tolist()
    y_pred = [
        label_from_compound(scores["compound"])
        for scores in engine.score_batch(texts)
    ]
    labels = ["positive", "neutral", "negative"]

    per_class: dict[str, float] = {}
    for label in labels:
        idx = [i for i, t in enumerate(y_true) if t == label]
        if idx:
            correct = sum(1 for i in idx if y_pred[i] == label)
            per_class[label] = correct / len(idx)
        else:
            per_class[label] = float("nan")

    return {
        "model": engine_name,
        "dataset": dataset_name,
        "samples": len(work),
        "accuracy": round(_accuracy(y_true, y_pred), 4),
        "macro_f1": round(_macro_f1(y_true, y_pred, labels), 4),
        "positive_acc": round(per_class.get("positive", float("nan")), 4),
        "neutral_acc": round(per_class.get("neutral", float("nan")), 4),
        "negative_acc": round(per_class.get("negative", float("nan")), 4),
    }


def load_dataset(name: str) -> pd.DataFrame:
    if name == "phrasebank":
        return load_financial_phrasebank_all_agree()
    if name == "combined":
        return load_combined_two_column_csv()
    if name == "all":
        return concat_training_views()
    raise ValueError(f"Unknown dataset: {name}")


def parse_models(raw: str) -> list[str]:
    if raw.strip().lower() in {"all", "both"}:
        return list(SUPPORTED_ENGINES)
    models = [part.strip().lower() for part in raw.split(",") if part.strip()]
    for model in models:
        if model not in SUPPORTED_ENGINES:
            raise ValueError(f"Unknown model {model!r}. Choose from: {', '.join(SUPPORTED_ENGINES)}")
    return models


def write_eval_summary(report: pd.DataFrame, path: Path = EVAL_SUMMARY_OUT) -> None:
    """Write a short human-readable summary next to sentiment_eval_report.csv."""
    if report.empty:
        return

    lines = [
        "# Sentiment model evaluation summary",
        "",
        "Auto-generated by `python -m src.evaluate_sentiment`. "
        "See `sentiment_eval_report.csv` for raw numbers.",
        "",
        "## Models",
        "",
        "- **VADER** — rule-based baseline (fast; used for live Dashboard scoring).",
        f"- **FinBERT** — finance-tuned transformer (`{FINBERT_MODEL_ID}`); integrated, not trained in this project.",
        "",
        "## Datasets",
        "",
        "- **phrasebank** — Financial PhraseBank (AllAgree subset); finance sentences with human labels.",
        "- **combined** — `all-data.csv` combined finance sentiment corpus (label + sentence).",
        "",
        "## Metrics",
        "",
        "- **accuracy** — overall label match rate.",
        "- **macro_f1** — average F1 across positive / neutral / negative.",
        "- **positive_acc / neutral_acc / negative_acc** — accuracy within each class.",
        "",
        "## Results",
        "",
        "| model | dataset | samples | accuracy | macro_f1 | pos | neu | neg |",
        "|-------|---------|---------|----------|----------|-----|-----|-----|",
    ]

    for _, row in report.iterrows():
        lines.append(
            f"| {row['model']} | {row['dataset']} | {int(row['samples'])} | "
            f"{row['accuracy']} | {row['macro_f1']} | {row['positive_acc']} | "
            f"{row['neutral_acc']} | {row['negative_acc']} |"
        )

    lines.extend(["", "## Takeaways", ""])

    for dataset in report["dataset"].unique():
        sub = report[report["dataset"] == dataset]
        vader = sub[sub["model"] == "vader"]
        finbert = sub[sub["model"] == "finbert"]
        if vader.empty or finbert.empty:
            continue
        va = float(vader.iloc[0]["accuracy"])
        fa = float(finbert.iloc[0]["accuracy"])
        delta = round((fa - va) * 100, 1)
        lines.append(
            f"- **{dataset}**: FinBERT accuracy **{fa:.1%}** vs VADER **{va:.1%}** "
            f"(+{delta} pp)."
        )

    lines.extend(
        [
            "",
            "## Deployment (IST 495 project)",
            "",
            "- **Live Dashboard** uses VADER so Finviz news can be scored in seconds.",
            "- **FinBERT** is used for offline pipeline runs and this benchmark comparison "
            "(professor roadmap item 6 — AI rankings).",
            "",
            "## Limitations",
            "",
            "- Benchmarks are labeled corpora, not live Finviz quote-page news.",
            "- FinBERT can underperform VADER on **neutral** text in the combined dataset; "
            "review per-class columns before production use.",
            "",
        ]
    )

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Evaluate sentiment models on benchmark datasets.")
    parser.add_argument(
        "--dataset",
        choices=["phrasebank", "combined", "all"],
        default="all",
        help="Benchmark dataset to evaluate",
    )
    parser.add_argument(
        "--models",
        default="vader",
        help="Comma-separated models (vader, finbert) or 'all'",
    )
    parser.add_argument("--out", type=Path, default=EVAL_OUT)
    args = parser.parse_args()

    models = parse_models(args.models)
    dataset_names = ("phrasebank", "combined") if args.dataset == "all" else (args.dataset,)

    records: list[dict[str, object]] = []
    for model in models:
        for name in dataset_names:
            try:
                df = load_dataset(name)
                records.append(evaluate_dataframe(df, name, engine_name=model))
            except (FileNotFoundError, UnicodeDecodeError, ValueError, OSError, RuntimeError) as exc:
                print(f"Skipping {model}/{name}: {exc}")

    report = pd.DataFrame.from_records(records)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    report.to_csv(args.out, index=False)
    write_eval_summary(report)

    vader_only = report[report["model"] == "vader"].drop(columns=["model"], errors="ignore")
    if not vader_only.empty:
        vader_only.to_csv(VADER_LEGACY_OUT, index=False)

    print(report.to_string(index=False))
    print(f"\nWrote report to {args.out}")
    print(f"Wrote summary to {EVAL_SUMMARY_OUT}")


if __name__ == "__main__":
    main()
